# Generated by Django 4.1 on 2022-09-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'classificacoes',
            },
        ),
        migrations.CreateModel(
            name='tipo_de_obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('foto_obra', models.CharField(max_length=300, null=True)),
                ('foto', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'tipos de obras',
            },
        ),
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(blank=True, max_length=45, null=True)),
                ('sinopse', models.CharField(blank=True, max_length=300, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.CharField(max_length=300)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guarda.classificacao')),
                ('tipo_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guarda.tipo_de_obra')),
            ],
            options={
                'verbose_name_plural': 'obras',
            },
        ),
    ]
