# Generated by Django 4.1.1 on 2022-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guarda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_de_obra',
            name='foto_obra',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
