# Generated by Django 4.1 on 2022-09-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guarda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_de_obra',
            name='foto',
        ),
    ]
