# Generated by Django 4.1.1 on 2022-09-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guarda', '0002_remove_tipo_de_obra_foto'),
        ('Guarda', '0002_tipo_de_obra_foto_obra'),
    ]

    operations = [
    ]
